import { useCallback, useEffect, useMemo, useState } from 'react'
import { getNotificationEvents } from '../api/notificationApi'
import Alert from '../components/Alert'
import Button from '../components/Button'
import { getErrorMessage } from '../utils/errors'
import { formatDateTime } from '../utils/format'

const stages = ['Account action', 'PostgreSQL', 'Kafka', 'FastStream', 'SMTP / MailDev']

const statusStyles = {
  PENDING: 'bg-amber-50 text-amber-800 ring-amber-200',
  PROCESSING: 'bg-blue-50 text-blue-800 ring-blue-200',
  SENT: 'bg-emerald-50 text-emerald-800 ring-emerald-200',
  FAILED: 'bg-red-50 text-red-800 ring-red-200',
}

const timelineStyles = {
  PENDING: 'bg-amber-500',
  PROCESSING: 'bg-blue-500',
  SENT: 'bg-emerald-500',
  FAILED: 'bg-red-500',
}

const eventLabels = {
  ACCOUNT_CREATED: 'Account created',
  ACCOUNT_UPDATED: 'Account updated',
  ACCOUNT_DELETED: 'Account deleted',
}

const statuses = ['PENDING', 'PROCESSING', 'SENT', 'FAILED']

function StatusBadge({ status }) {
  const style = statusStyles[status] || 'bg-slate-100 text-slate-700 ring-slate-200'
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ring-inset ${style}`}>{status || 'UNKNOWN'}</span>
}

function EventDetails({ event }) {
  const details = [
    ['Event ID', event.id || 'Not available'],
    ['Event type', event.event_type || 'Not available'],
    ['Recipient', event.recipient || 'Not available'],
    ['Status', event.status || 'Not available'],
    ['Created', formatDateTime(event.created_at)],
    ['Processed', event.processed_at ? formatDateTime(event.processed_at) : 'Not processed yet'],
  ]

  return (
    <details className="mt-4 rounded-lg border border-slate-200 bg-slate-50/70 px-4 py-3">
      <summary className="cursor-pointer text-sm font-semibold text-indigo-700 outline-none focus-visible:rounded focus-visible:ring-2 focus-visible:ring-indigo-500">View event details</summary>
      <dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2">
        {details.map(([label, value]) => <div key={label} className="min-w-0"><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 break-all text-slate-700">{value}</dd></div>)}
      </dl>
    </details>
  )
}

export default function EmailActivity() {
  const [events, setEvents] = useState([])
  const [statusFilter, setStatusFilter] = useState('ALL')
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState('')

  const loadEvents = useCallback(async () => {
    setIsLoading(true)
    setError('')
    try {
      const response = await getNotificationEvents()
      setEvents(Array.isArray(response) ? response : [])
    } catch (requestError) {
      setError(getErrorMessage(requestError, 'We could not load your email activity.'))
    } finally {
      setIsLoading(false)
    }
  }, [])

  useEffect(() => {
    loadEvents()
  }, [loadEvents])

  const filteredEvents = useMemo(
    () => statusFilter === 'ALL' ? events : events.filter((event) => event.status === statusFilter),
    [events, statusFilter],
  )

  return (
    <div className="mx-auto max-w-4xl space-y-8">
      <section><p className="text-sm font-medium text-indigo-600">Asynchronous processing</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">Email Activity</h1><p className="mt-2 text-sm text-slate-500">Lifecycle email events generated by your account actions.</p></section>
      <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-card sm:p-6">
        <div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-semibold text-slate-900">Notification history</h2><p className="mt-1 text-sm text-slate-500">Events are shown newest first from your authenticated account history.</p></div><Button variant="secondary" onClick={loadEvents} loading={isLoading}>{isLoading ? 'Refreshing…' : 'Refresh'}</Button></div>
        <div className="mt-6 flex flex-col gap-3 border-y border-slate-100 py-4 sm:flex-row sm:items-center sm:justify-between"><label className="flex items-center gap-3 text-sm font-medium text-slate-700" htmlFor="event-status-filter">Status <select id="event-status-filter" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)} className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-700 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100"><option value="ALL">All statuses</option>{statuses.map((status) => <option key={status} value={status}>{status}</option>)}</select></label><p className="text-sm text-slate-500">{filteredEvents.length} {filteredEvents.length === 1 ? 'event' : 'events'}</p></div>
        {error && <div className="mt-5 space-y-3"><Alert>{error}</Alert><Button variant="secondary" onClick={loadEvents}>Try again</Button></div>}
        {isLoading && !events.length ? <div className="py-10 text-center" role="status"><span className="mx-auto block h-6 w-6 animate-spin rounded-full border-2 border-indigo-600 border-r-transparent" aria-hidden="true" /><p className="mt-3 text-sm text-slate-500">Loading notification history…</p></div> : null}
        {!isLoading && !error && !events.length ? <div className="py-10 text-center"><h3 className="text-sm font-semibold text-slate-800">No email activity yet</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Lifecycle events will appear here after you register, update your profile, or delete your account.</p></div> : null}
        {!isLoading && !error && events.length > 0 && !filteredEvents.length ? <div className="py-10 text-center"><h3 className="text-sm font-semibold text-slate-800">No matching events</h3><p className="mt-2 text-sm text-slate-500">Try another status to see the rest of your notification history.</p></div> : null}
        {filteredEvents.length > 0 ? <div className="mt-7 space-y-0">{filteredEvents.map((event, index) => <article key={event.id} className="relative flex gap-4 pb-7 last:pb-0"><div className="relative z-10 flex w-5 justify-center"><span className={`mt-1.5 h-2.5 w-2.5 rounded-full ${timelineStyles[event.status] || 'bg-slate-400'}`} />{index < filteredEvents.length - 1 && <span className="absolute top-5 h-full w-px bg-slate-200" />}</div><div className="min-w-0 flex-1 pb-1"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="text-sm font-semibold text-slate-900">{eventLabels[event.event_type] || event.event_type || 'Lifecycle event'}</h3><p className="mt-1 break-all text-sm text-slate-500">To {event.recipient || 'recipient unavailable'}</p></div><StatusBadge status={event.status} /></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Created</dt><dd className="mt-1 font-medium text-slate-700">{formatDateTime(event.created_at)}</dd></div><div><dt className="text-slate-500">Processed</dt><dd className="mt-1 font-medium text-slate-700">{event.processed_at ? formatDateTime(event.processed_at) : 'Not processed yet'}</dd></div></dl><EventDetails event={event} /></div></article>)}</div> : null}
      </section>
      <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-card sm:p-6"><h2 className="text-lg font-semibold text-slate-900">Email processing architecture</h2><p className="mt-1 text-sm text-slate-500">This is the backend flow, not live telemetry.</p><div className="mt-7 flex flex-col items-stretch gap-2 sm:flex-row sm:items-center sm:justify-between sm:gap-0">{stages.map((stage, index) => <div key={stage} className="contents"><div className="rounded-lg border border-slate-200 bg-slate-50 px-4 py-3 text-center text-sm font-semibold text-slate-700 sm:min-w-28">{stage}</div>{index < stages.length - 1 && <div className="text-center text-slate-300 sm:px-2" aria-hidden="true">↓<span className="hidden sm:inline"> →</span></div>}</div>)}</div></section>
      <section className="rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="text-sm font-semibold text-amber-900">About email status</h2><p className="mt-1.5 text-sm leading-6 text-amber-800">SENT means the current email operation succeeded. It does not confirm inbox delivery, opening, or recipient engagement.</p></section>
    </div>
  )
}
