const events = [
  { name: 'Account Created', description: 'Generated after successful account registration.', color: 'bg-emerald-500' },
  { name: 'Account Updated', description: 'Generated after a profile change is saved.', color: 'bg-indigo-500' },
  { name: 'Account Deleted', description: 'Generated when an account is successfully deleted.', color: 'bg-red-500' },
]

const stages = ['Account action', 'PostgreSQL', 'Kafka', 'FastStream', 'SMTP / MailDev']

export default function EmailActivity() {
  return (
    <div className="mx-auto max-w-4xl space-y-8">
      <section><p className="text-sm font-medium text-indigo-600">Asynchronous processing</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">Email Activity</h1><p className="mt-2 text-sm text-slate-500">Account lifecycle email events generated by your actions.</p></section>
      <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-card sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold text-slate-900">Lifecycle Events</h2><p className="mt-1 text-sm text-slate-500">The backend generates these events; it does not currently expose delivery history or status.</p></div><span className="shrink-0 rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-600">Backend capability</span></div><div className="mt-7 space-y-0">{events.map((event, index) => <div key={event.name} className="relative flex gap-4 pb-7 last:pb-0"><div className="relative z-10 flex w-5 justify-center"><span className={`mt-1.5 h-2.5 w-2.5 rounded-full ${event.color}`} />{index < events.length - 1 && <span className="absolute top-5 h-full w-px bg-slate-200" />}</div><div><h3 className="text-sm font-semibold text-slate-800">{event.name}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{event.description}</p></div></div>)}</div></section>
      <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-card sm:p-6"><h2 className="text-lg font-semibold text-slate-900">Email processing architecture</h2><p className="mt-1 text-sm text-slate-500">This is the backend flow, not live telemetry.</p><div className="mt-7 flex flex-col items-stretch gap-2 sm:flex-row sm:items-center sm:justify-between sm:gap-0">{stages.map((stage, index) => <div key={stage} className="contents"><div className="rounded-lg border border-slate-200 bg-slate-50 px-4 py-3 text-center text-sm font-semibold text-slate-700 sm:min-w-28">{stage}</div>{index < stages.length - 1 && <div className="text-center text-slate-300 sm:px-2" aria-hidden="true">↓<span className="hidden sm:inline"> →</span></div>}</div>)}</div></section>
      <section className="rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="text-sm font-semibold text-amber-900">What you can see today</h2><p className="mt-1.5 text-sm leading-6 text-amber-800">Detailed delivery history will be available when notification tracking is enabled. Until then, AccountFlow intentionally does not show sent, delivered, failed, timestamps, or event records that the backend does not provide.</p></section>
    </div>
  )
}
